---
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvx_app
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
  jackson:
#    deserialization.UNWRAP_ROOT_VALUE: true
    serialization:
#      WRAP_ROOT_VALUE: true
      WRITE_DATES_AS_TIMESTAMPS: false

security:
  jwt:
    token:
      secretKey: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
      validityInMs: 3600000 # 1 HOUR
