---
logging:
  level:
    org.springframework: INFO
    org.axonframework: INFO

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/dvx_app
    driver-class-name: org.postgresql.Driver
    username: ${USER}
    password:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  data:
    jdbc:
      repositories:
        enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: validate
      hibernate.format_sql: false
    generate-ddl: false
    show-sql: false

  flyway:
    enabled: true
    user: ${USER}
    password:

  jackson:
#    deserialization.UNWRAP_ROOT_VALUE: true
    serialization:
#      WRAP_ROOT_VALUE: true
      WRITE_DATES_AS_TIMESTAMPS: false

security:
  jwt:
    token:
      secretKey: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
      validityInMs: 3600000 # 1 HOUR

axon:

  axonserver:
    servers: axonserver.cloud.axoniq.io:443
    keep-alive-time: 0
    ssl-enabled: true
    context: user@dvx-base
    token: wfqmu3bVhlgbLI5aztNm

  serializer:
    general: jackson
    events: jackson
    messages: jackson

  #see: https://axoniq.io/blog-overview/set-based-validation
  eventhandling:
    processors:
      indexEntity.mode: subscribing
