---
logging:
  level:
    org.springframework: INFO
    io.liquidsoftware: DEBUG

server:
  error:
    include-message: always

spring:

  config:
    import:
      - classpath:common.yml

  data:
    mongodb:
      database: modulith-mongo
      uri: mongodb://localhost:27017/

  jackson:
#    deserialization.UNWRAP_ROOT_VALUE: true
    serialization:
#      WRAP_ROOT_VALUE: true
      WRITE_DATES_AS_TIMESTAMPS: false

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss

security:
  jwt:
    token:
      secretKey: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
      validityInMs: 3600000 # 1 HOUR
